version: '3'

services:

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=plannerdb
        #network_mode: host    
    ports:
      - 5432:5432
    networks:
      - frontend
networks: 
  frontend:
     name: frontend 